<?php
/**
 * Implements   hook_menu().
 */
function dolist_campaign_sms_menu() {
  $items['admin/structure/dolist/campaignssms'] = array(
    'title' => 'Campaign Sms',
    'description' => 'Manage Dolist Campaigns Sms',
    'page arguments' => array('dolist_campaign_campaign_sms_form'),
    'page callback' => 'campaign_sms_overview_page',
    'access arguments' => array('administer dolist campaign sms'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dolist_campaign_sms.admin.inc',
    'weight' => 10
  );

  $items['admin/structure/dolist/campaignssms/notsend'] = array(
    'title' => 'Not Send',
    'page arguments' => array('dolist_campaign_campaign_sms_form'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'dolist_campaign_sms.admin.inc',
    'weight' => -10,
  );
  $items['admin/structure/dolist/campaignssms/send'] = array(
    'title' => 'Send',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'campaign_sms_send_overview_page',
    'page arguments' => array('dolist_campaign_campaign_form'),
    'access arguments' => array('administer dolist campaign sms'),
    'file' => 'dolist_campaign_sms.admin.inc',
  );

  $items['admin/structure/dolist/campaignssms/add'] = array(
    'title' => 'Add a Campaign Sms',
    'description' => 'Add a new Dolist campaign Sms.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dolist_campaign_sms_form'),
    'access arguments' => array('administer dolist campaign sms'),
    'file' => 'dolist_campaign_sms.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

   $items['admin/structure/dolist/campaignssms/%/simulate'] = array(
    'title' => 'Simulate a Campaign Sms sending',
    'description' => 'Simulate a Campaign Sms sending',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dolist_campaign_sms_simulate_form',4),
    'load arguments' => array(6),
    'access arguments' => array('administer dolist campaign sms'),
    'file' => 'dolist_campaign_sms.admin.inc',
  );

  $items['admin/structure/dolist/campaignssms/%/sendtest'] = array(
    'title' => 'Send a BAT',
    'description' => 'Test campaign sms sending',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dolist_campaign_sms_sendtest_form',4),
    'load arguments' => array(6),
    'access arguments' => array('administer dolist campaign sms'),
    'file' => 'dolist_campaign_sms.admin.inc',
  );

  $items['admin/structure/dolist/campaignssms/%/sendreal'] = array(
    'title' => 'Send a campaign sms',
    'description' => 'Send a campaign sms',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dolist_campaign_sms_sendreal_form',4),
    'load arguments' => array(6),
    'access arguments' => array('administer dolist campaign sms'),
    'file' => 'dolist_campaign_sms.admin.inc',
  );

  return $items;
}

  
function dolist_campaign_sms_entity_info() {
  $return = array(
    'campaignsms' => array(
      'label' => t('Campaign Sms'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'Entity',
      'base table' => 'campaignsms',
      'fieldable' => FALSE,
      'entity keys' => array(
        'id' => 'nid',
      ),
    ),
  );
  return $return;
}

/**
 * Implements hook_permission().
 */
function dolist_campaign_sms_permission() {
  return array(
    'administer dolist campaign sms' => array(
      'title' => t('Access content to campaign sms'),
    )
  );
}


?>