<?php
/**
 * Implements   hook_menu().
 */
function dolist_segments_menu() {
  $items['admin/config/services/dolist/segments'] = array(
    'title' => 'Segments',
    'description' => 'Manage Dolist Segments.',
    'page arguments' => array('dolist_segments_form'),
    'access arguments' => array('administer dolist Segments'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dolist_segments.admin.inc',
    'weight' => 10
  );
  $items['admin/config/services/dolist/segments/add'] = array(
    'title' => 'Add a new Segment',
    'description' => 'Add a new Dolist Segment',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dolist_segments_form'),
    'access arguments' => array('administer mailchimp segments'),
    'file' => 'dolist_segments.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

 

  return $items;
}


?>
