<?php
/**
 * Implements   hook_menu().
 */
function dolist_segments_menu() {
   $items['admin/structure/dolist/segments'] = array(
    'title' => 'Segments',
    'description' => 'Manage Dolist Segments.',
    'page arguments' => array('dolist_segments_form'),
    'page callback' => 'segments_overview_page',
    'access arguments' => array('administer dolist Segments'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dolist_segments.admin.inc',
    'weight' => 10
  );


  return $items;
}

function segments_overview_page(){
 $api=new dolistAPI(variable_get('global_settings_api_key'),
  variable_get('global_settings_account_id'));
  $result=$api->getAllSegments();
 $rows = array();
 foreach ($result as $key=>$segment) {
        
     $rows[] = array(
      $segment->Name,
      $segment->Id,
      $segment->ContactsCount,
      $newDate = date("d F Y H:i", strtotime($segment->CreationDate))
      );
 }
    return array(
    '#theme' => 'table',
    '#header' => array(
      t('Nom'),
      t('ID'),
      t('Nombre de contacts'),
      t('Date de Création')
    ),
     '#rows' => $rows
  );
}

?>
