<?php
/**
 * Implements   hook_menu().
 */
function dolist_campaign_mail_menu() {
  $items['admin/config/services/dolist/campaignsmail'] = array(
    'title' => 'Campaign Mail',
    'description' => 'Manage Dolist Campaigns Mail',
    'page arguments' => array('dolist_campaign_campaign_mail_form'),
    'access arguments' => array('administer dolist campaigns mail'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dolist_campaign_mail.admin.inc',
    'weight' => 10
  );
  $items['admin/config/services/dolist/campaignsmail/add'] = array(
    'title' => 'Add a Campaign Mail',
    'description' => 'Add a new Dolist campaign Mail.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dolist_campaign_campaign_mail_form'),
    'access arguments' => array('administer mailchimp campaigns'),
    'file' => 'dolist_campaign_mail.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  return $items;
}



?>