<?php
/**
 * Implements   hook_menu().
 */
function dolist_messages_mail_menu() {
  $items['admin/config/services/dolist/messagesmail'] = array(
    'title' => 'Message Mail',
    'description' => 'Manage Dolist Messages',
    'page arguments' => array('dolist_messages_mail_form'),
    'access arguments' => array('administer dolist Messages'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dolist_messages_mail.admin.inc',
    'weight' => 10
  );
  $items['admin/config/services/dolist/messagesmail/add'] = array(
    'title' => 'Add a new Message Type',
    'description' => 'Add a new Dolist Message Type',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dolist_messages_add_form'),
    'access arguments' => array('administer dolist Messages'),
    'file' => 'dolist_messages_mail.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

 

  return $items;
}



?>