<?php
/**
 * Implements   hook_menu().
 */
function dolist_contacts_menu() {
  $items['admin/config/services/dolist/contacts'] = array(
    'title' => 'Contacts',
    'description' => 'Manage Dolist Contacts',
    'page arguments' => array('dolist_contacts_form'),
    'access arguments' => array('administer dolist contacts'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dolist_contacts.admin.inc',
    'weight' => 10
  );
  $items['admin/config/services/dolist/contacts/add'] = array(
    'title' => 'Add a new Contact',
    'description' => 'Add a new Dolist Contact',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dolist_contacts_form'),
    'access arguments' => array('administer mailchimp contacts'),
    'file' => 'dolist_contacts.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

 

  return $items;
}


?>